# """
#     The MIT License (MIT)

#     Copyright (c) 2023 pkjmesra

#     Permission is hereby granted, free of charge, to any person obtaining a copy
#     of this software and associated documentation files (the "Software"), to deal
#     in the Software without restriction, including without limitation the rights
#     to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#     copies of the Software, and to permit persons to whom the Software is
#     furnished to do so, subject to the following conditions:

#     The above copyright notice and this permission notice shall be included in all
#     copies or substantial portions of the Software.

#     THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#     IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#     FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#     AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#     LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#     OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#     SOFTWARE.

# """
FROM mcr.microsoft.com/windows:10.0.17763.4645-amd64 as base-image
RUN powershell.exe -Command \
    $ErrorActionPreference = 'Stop'; \
    wget https://www.python.org/ftp/python/3.9.13/python-3.9.13.exe -OutFile c:\python-3.9.13.exe ; \
    Start-Process c:\python-3.9.13.exe -ArgumentList '/quiet InstallAllUsers=1 PrependPath=1' -Wait ; \
    Remove-Item c:\python-3.9.13.exe -Force
FROM scratch

COPY --from=base-image ["/", "/"]

RUN git clone https://github.com/pkjmesra/pkscreener.git

WORKDIR /pkscreener-main/

RUN tar -xf ./.github/dependencies/ta-lib-0.4.0-msvc.zip

RUN pip3 install --upgrade pip
RUN pip install ./.github/dependencies/TA_Lib-0.4.19-cp39-cp39-win_amd64.whl
RUN pip3 install -r requirements.txt
RUN pip3 install ta-lib
RUN pip3 install .

RUN cd pkscreener

RUN python3 ./pkscreenercli.py
