# """
#     The MIT License (MIT)

#     Copyright (c) 2023 pkjmesra

#     Permission is hereby granted, free of charge, to any person obtaining a copy
#     of this software and associated documentation files (the "Software"), to deal
#     in the Software without restriction, including without limitation the rights
#     to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#     copies of the Software, and to permit persons to whom the Software is
#     furnished to do so, subject to the following conditions:

#     The above copyright notice and this permission notice shall be included in all
#     copies or substantial portions of the Software.

#     THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#     IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#     FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#     AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#     LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#     OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#     SOFTWARE.

# """
FROM pkjmesra/ta-lib-debian_gnu_linux:latest as base-image
ENV PYTHONUNBUFFERED 1

FROM scratch

# RUN echo "deb http://security.debian.org/debian-security bullseye-security main contrib non-free" > /etc/apt/sources.list
# RUN apt-get update

COPY --from=base-image ["/", "/"]
ARG GIT_RUN_NUMBER
RUN apt-get -y install libc-dev
RUN apt-get update && apt-get -y install build-essential

WORKDIR /
RUN rm -rf PKScreener-*

RUN apt-get -y install unzip
RUN wget https://github.com/pkjmesra/pkscreener/archive/main.zip && \
  unzip main.zip && \
  rm -rf main.zip

WORKDIR PKScreener-main

RUN pip3 install --upgrade pip
RUN python3 -m pip install setuptools
RUN pip install --upgrade setuptools
RUN pip install packages
RUN pip3 install -r requirements.txt
RUN pip3 install ta-lib
RUN export CURRENT_VERSION=`grep -o "'.*'" pkscreener/classes/__init__.py | sed "s/'//g"` \
    && echo VERSION=\'`echo ${CURRENT_VERSION}`\' \
    && export TODAY=`date +%Y%m%d` \
    && export THIS_VERSION=${CURRENT_VERSION}.${TODAY}.${GIT_RUN_NUMBER} \
    && rm -rf pkscreener/classes/__init__.py \
    && echo VERSION=\'`echo ${THIS_VERSION}`\' >> pkscreener/classes/__init__.py \
    && echo VERSION=\'`echo ${THIS_VERSION}`\'
RUN pip3 install .
RUN wget https://github.com/taveevut/Windows-10-Fonts-Default/raw/master/courbd.ttf && \
  cp courbd.ttf /usr/local/share/fonts/courbd.ttf
WORKDIR pkscreener
# RUN python3 pkscreenercli.py
