FROM pkjmesra/ta-lib-alpine:latest as base-image
ENV PYTHONUNBUFFERED 1

FROM scratch

# RUN echo "deb http://security.debian.org/debian-security bullseye-security main contrib non-free" > /etc/apt/sources.list
# RUN apt-get update

COPY --from=base-image ["/", "/"]

ENV PYTHON_VERSION 3.7.10-r0
ENV PYTHON_VERSION_1 3.11.4-r1

# RUN apt-get -y install libc-dev
# RUN apt-get update && apt-get -y install build-essential

WORKDIR /

RUN apk add --no-cache python3=${PYTHON_VERSION} && \
  apk add git && \
  git clone https://github.com/pkjmesra/pkscreener.git

RUN apk add --no-cache python3=${PYTHON_VERSION_1}
WORKDIR pkscreener

RUN pip3 install --upgrade pip
RUN python3 -m pip install setuptools
RUN pip install --upgrade setuptools
RUN apk add py3-scipy
RUN apk add py3-scikit-learn
RUN pip3 install -r requirements-alpine.txt
WORKDIR pkscreener
# RUN python3 pkscreener.py
