FROM pkjmesra/ta-lib-debian_gnu_linux:latest as base-image
ENV PYTHONUNBUFFERED 1

FROM scratch

# RUN echo "deb http://security.debian.org/debian-security bullseye-security main contrib non-free" > /etc/apt/sources.list
# RUN apt-get update

COPY --from=base-image ["/", "/"]

RUN apt-get -y install libc-dev
RUN apt-get update && apt-get -y install build-essential

WORKDIR /
RUN rm -rf PKScreener-*

RUN apt-get -y install unzip
RUN wget https://github.com/pkjmesra/pkscreener/archive/main.zip && \
  unzip main.zip && \
  rm -rf main.zip

WORKDIR PKScreener-main

RUN pip3 install --upgrade pip
RUN python3 -m pip install setuptools
RUN pip install --upgrade setuptools
RUN pip install packages
RUN pip3 install -r requirements.txt

WORKDIR src
# RUN python3 pkscreener.py
