# """
#     The MIT License (MIT)

#     Copyright (c) 2023 pkjmesra

#     Permission is hereby granted, free of charge, to any person obtaining a copy
#     of this software and associated documentation files (the "Software"), to deal
#     in the Software without restriction, including without limitation the rights
#     to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#     copies of the Software, and to permit persons to whom the Software is
#     furnished to do so, subject to the following conditions:

#     The above copyright notice and this permission notice shall be included in all
#     copies or substantial portions of the Software.

#     THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#     IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#     FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#     AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#     LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#     OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#     SOFTWARE.

# """
FROM pkjmesra/ta-lib-alpine:latest as base-image
ENV PYTHONUNBUFFERED 1

FROM scratch

# RUN echo "deb http://security.debian.org/debian-security bullseye-security main contrib non-free" > /etc/apt/sources.list
# RUN apt-get update

COPY --from=base-image ["/", "/"]

ENV PYTHON_VERSION 3.7.10-r0
ENV PYTHON_VERSION_1 3.11.4-r1

# RUN apt-get -y install libc-dev
# RUN apt-get update && apt-get -y install build-essential

WORKDIR /

RUN apk add --no-cache python3=${PYTHON_VERSION} && \
  apk add git && \
  git clone https://github.com/pkjmesra/pkscreener.git

RUN apk add --no-cache python3=${PYTHON_VERSION_1}
WORKDIR pkscreener

RUN pip3 install --upgrade pip
RUN python3 -m pip install setuptools
RUN pip install --upgrade setuptools
RUN apk add py3-scipy
RUN apk add py3-scikit-learn
RUN pip3 install -r requirements-alpine.txt
RUN pip3 install .
WORKDIR pkscreener
# RUN python3 pkscreenercli.py
